---
- name: install ntp package
  package:
    name: ntp
    state: present

- name: template /etc/ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp

- name: maintain ntp service
  service:
    name: ntp
    enabled: true
    state: started
