---
driver:
  name: vagrant
vagrant:
  platforms:
    - name: xenial64
      box: ubuntu/xenial64
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 2
  instances:
    - name: apache2
      ansible_groups:
        - group1
verifier:
  name: testinfra
