---
- name: install openvswitch
  package:
    name: openvswitch-switch
    state: present

- name: maintain openvswitch-switch service
  service:
    name: openvswitch-switch
    enabled: true
    state: started
