---
driver:
  name: vagrant
vagrant:
  platforms:
    - name: xenial64
      box: ubuntu/xenial64
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 2048
        cpus: 2
  instances:
    - name: neutron-server
      ansible_groups:
        - neutron-api
      interfaces:
        - network_name: private_network
          type: static
          ip: 192.168.33.10
          auto_config: false
verifier:
  name: testinfra
